name: Notify and Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  notify-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install mailutils
      run: sudo apt-get update && sudo apt-get install -y mailutils
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Send Email on Pull Request
      if: github.event.action == 'opened'
      run: |
        echo "Pull request #${{ github.event.pull_request.number }} created by @${{ github.event.pull_request.user.login }}. Title: ${{ github.event.pull_request.title }}." | mail -s "New Pull Request" raam42devops@gmail.com
    
    - name: Check for merge conflicts
      run: |
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
        if ! git merge-tree $(git merge-base origin/${{ github.event.pull_request.base.ref }} HEAD) HEAD origin/${{ github.event.pull_request.head.ref }} | grep -q '<<<<<<<'; then
          echo "No merge conflicts"
        else
          echo "Merge conflicts detected"
          exit 1
      shell: bash
    
    - name: Send Email on Merge Conflict
      if: failure()
      run: |
        echo "Merge conflicts detected in PR #${{ github.event.pull_request.number }} by @${{ github.event.pull_request.user.login }}. Please resolve conflicts." | mail -s "Merge Conflict Alert" raam42devops@gmail.com
    
    - name: Merge PR
      if: success()
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout ${{ github.event.pull_request.base.ref }}
        git merge ${{ github.event.pull_request.head.ref }} -m "Merging PR #${{ github.event.pull_request.number }} from ${{ github.event.pull_request.user.login }}"
        git push origin ${{ github.event.pull_request.base.ref }}
